# Generated by Django 5.2.5 on 2025-09-19 19:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEmail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Mã UUID')),
                ('to', models.EmailField(max_length=254, verbose_name='Gửi đến')),
                ('cc', models.CharField(blank=True, max_length=256, null=True)),
                ('bcc', models.CharField(blank=True, max_length=256, null=True)),
                ('subject', models.CharField(max_length=256, verbose_name='Chủ đề')),
                ('template_name', models.CharField(choices=[('test_email', 'TEST')], max_length=128, verbose_name='Tên mẫu')),
                ('context', models.JSONField(blank=True, null=True, verbose_name='Tham số')),
                ('status', models.CharField(choices=[('Đợi', 'PENDING'), ('Đã gửi', 'SENT'), ('Lỗi', 'FAILED')], default='Đợi', max_length=16, verbose_name='Trạng thái')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Lỗi')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian gửi')),
            ],
            options={
                'verbose_name': 'Nhật ký gửi mail',
                'verbose_name_plural': 'Nhật ký gửi mail',
                'db_table': 'log_emails',
            },
        ),
    ]
