# Generated by Django 5.2.5 on 2025-09-13 09:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to', models.EmailField(max_length=254)),
                ('cc', models.CharField(blank=True, max_length=255, null=True)),
                ('bcc', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('template_name', models.CharField(max_length=128)),
                ('context', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Đợi', 'Pending'), ('Đã gửi', 'Sent'), ('Lỗi', 'Failed')], default='Đợi', max_length=16)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'email_logs',
                'ordering': ['-updated_at'],
            },
        ),
    ]
