# Generated by Django 5.2.5 on 2025-09-15 04:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEmail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Được tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Được cập nhật lúc')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Mã UUID')),
                ('to', models.EmailField(max_length=254, verbose_name='Gửi đến')),
                ('cc', models.CharField(blank=True, max_length=256, null=True)),
                ('bcc', models.CharField(blank=True, max_length=256, null=True)),
                ('subject', models.CharField(max_length=256, verbose_name='Chủ đề')),
                ('template_name', models.CharField(max_length=128, verbose_name='Tên mẫu')),
                ('context', models.JSONField(blank=True, null=True, verbose_name='Tham số')),
                ('status', models.CharField(choices=[('Đợi', 'Pending'), ('Đã gửi', 'Sent'), ('Lỗi', 'Failed')], default='Đợi', max_length=16, verbose_name='Trạng thái')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Lỗi')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Được gửi lúc')),
            ],
            options={
                'db_table': 'log_emails',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.DeleteModel(
            name='EmailLog',
        ),
    ]
