version: "3"

services:
  redis:
    image: redis:latest
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis/data:/data
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
