version: "3"

services:
  redis:
    image: redis:latest
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis/data:/data
    restart: always
    command: ["redis-server", "--appendonly", "yes"]

  postgres:
    image: postgres:latest
    container_name: ${COMPOSE_PROJECT_NAME}_postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    restart: always
