# Generated by Django 5.2.5 on 2025-09-22 15:42

import django.db.models.deletion
import upload.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('original_name', models.CharField(max_length=256)),
                ('file', models.FileField(upload_to=upload.models.upload_path)),
                ('visibility', models.CharField(choices=[('Công khai', 'PUBLIC'), ('Chỉ mình tôi', 'PRIVATE')], default='Chỉ mình tôi', max_length=16)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quản lý file',
                'verbose_name_plural': 'Quản lý file',
                'db_table': 'files_manager',
            },
        ),
    ]
