global:
  resolve_timeout: 5m
  smtp_smarthost: ${SMTP_SMARTHOST}
  smtp_from: ${SMTP_USER}
  smtp_auth_username: ${SMTP_USER}
  smtp_auth_password: ${SMTP_PASS}
  smtp_require_tls: true

route:
  receiver: 'email-alert'

receivers:
  - name: 'email-alert'
    email_configs:
      - to: ${SMTP_USER}
