# Generated by Django 5.2.5 on 2025-09-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Quản trị', 'ADMIN')], null=True, verbose_name='Vai trò'),
        ),
    ]
