# Generated by Django 5.2.5 on 2025-09-15 04:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Mã UUID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, max_length=16, verbose_name='Mức độ')),
                ('message', models.TextField(verbose_name='Tin nhắn')),
                ('location', models.CharField(max_length=256, verbose_name='Vị trí')),
                ('exception_type', models.CharField(blank=True, max_length=128, null=True, verbose_name='Loại ngoại lệ')),
                ('exc', models.TextField(blank=True, null=True, verbose_name='Ngoại lệ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Được tạo lúc')),
            ],
            options={
                'db_table': 'log_entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
