# Generated by Django 5.2.5 on 2025-09-19 19:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Mã UUID')),
                ('path', models.CharField(max_length=256, verbose_name='URL')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], max_length=16, verbose_name='Phương thức')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('status_code', models.PositiveSmallIntegerField(verbose_name='Mã')),
                ('response_time_ms', models.PositiveIntegerField(verbose_name='Thời gian (ms)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Nhật ký yêu cầu',
                'verbose_name_plural': 'Nhật ký yêu cầu',
                'db_table': 'log_requests',
            },
        ),
    ]
