name: Python Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install pylint isort autopep8

      - name: Check import order with isort
        run: isort src --check-only --diff

      - name: Run pylint
        run: pylint src
